"""add driver verification

Revision ID: 302842bccde4
Revises: 22c61a26368e
Create Date: 2026-01-12 20:59:20.044200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302842bccde4'
down_revision = '22c61a26368e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_status')
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###
