"""Add checkout_request_id to payments

Revision ID: 8856cd704064
Revises: db7814d56a94
Create Date: 2026-01-14 14:35:48.321728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8856cd704064'
down_revision = 'db7814d56a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['checkout_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
