"""Add assignment_status to Matatu

Revision ID: b03ae2f22f27
Revises: 4455a706e08d
Create Date: 2026-01-10 23:51:44.061266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03ae2f22f27'
down_revision = '4455a706e08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matatus', schema=None) as batch_op:
        batch_op.drop_column('assignment_status')

    # ### end Alembic commands ###
