"""Add sacco_id to User

Revision ID: c9743705c4a2
Revises: b03ae2f22f27
Create Date: 2026-01-11 00:09:44.997773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9743705c4a2'
down_revision = 'b03ae2f22f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sacco_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sacco_id')

    # ### end Alembic commands ###
